### ISSUE TITLE
Lookup tables to allow user with permission to edit/add/remove lines

### ISSUE THREAD

**Issue by nmadruga** [msupply-foundation/conforma-web-app#1048]
Improving Lookup-tables issue 2: UX on **Lookup tables** page. 

Currently the lookups table can only be imported/exported. And in order to update (edit a line, add a line or delete) it's required that the user first exports the existing CVS and do the changes externally before re-importing it. This workflow isn't the ideal and it has some flaws. One example is to re-upload a list from scratch, since we compare IDs, it's not simple to export then combine the new CVS before importing to refresh the existing table.

**This proposed solution doesn't solve the problem entirely!** Since it would still be a problem when wanting to refresh the table. The goal is to allow the user with small changes by not needed to export/import every time the user wants to make a small change on the table.
On the lookup tables page users (with permission to) should be able to add a new line, remove existing lines and edit.
This idea is part of what has been already discussed with customer is Angola, and for that reason has the tag for this client.
This issue is associated with the work already started for https://github.com/openmsupply/conforma-server/issues/629
Missing items to complete the work should be done in this issue covering points 3, 4 & 5.

The list of issues to improve Lookup tables includes:
- Issue 1: Disassociate permissions to edit/view lookup table from only-admin users - https://github.com/openmsupply/conforma-server/issues/816
- Issue 2: **current** - this should complete the work (for items 3, 4 & 5) in more details https://github.com/openmsupply/conforma-server/issues/629
- Issue 3: TODO - Allow re-importing one CVS to update many records at a time (removing the need for exporting first to match IDs)

**Comment by CarlosNZ** [comment]
Done
