### ISSUE TITLE
Problem with Template_element with dot in the code

### ISSUE THREAD

**Issue by nmadruga** [msupply-foundation/conforma-web-app#1327]
When trying to use this code on one of the actions that map values into an object, it would always retrieve NULL. So the solution needs to be: fix where it's creating the problem or make it not possible to use dots in the code of a template_element

**Comment by CarlosNZ** [comment]
It's just Javascript. Dots have semantic meaning in Javascript, so they can't be used in property or variable names, so it's the same here.

Anyone who doesn't understand what's going on with object paths shouldn't be allowed anywhere near the template builder.

Seems like a pretty low priority thing to worry about. The logic to enforce this everywhere would be super messy and take a long time to do properly. And there'd still be a hundred different ways you can still break templates if you don't know what you're doing.

**Comment by CarlosNZ** [comment]
Okay, there's a simple way to enforce this at the database level:

https://stackoverflow.com/questions/46673217/postgresql-check-constraint-to-limit-specific-characters

So we can do this quickly and without having to make a mess in the front-end.
