### ISSUE TITLE
Lookup tables: Allow re-importing one CSV to update many records at a time

### ISSUE THREAD

**Issue by nmadruga** [msupply-foundation/conforma-web-app#1467]
Improving Lookup-tables issue 3: Re-importing lookup table

Currently the lookups table can only be imported/exported. And in order to update (edit a line, add a line or delete) it's required that the user first exports the existing CSV and do the changes externally before re-importing it. The [issue 2](https://github.com/openmsupply/conforma-web-app/issues/1048) deals with single lines in the lookup table, although to get it fully replaced be re-importing a similar list with edited added and removed elements is a bit more complicated.

We would need to have a different unique field to be the ID, so we don't rely on the system created IDs that need to be exported, updated before re-importing. We should be able to select which is the unique column to use - which couldn't be edit - and that would be different per lookup table. This "unique" column selected is stored in the data_view table in the system.

When the table is re-imported each line is checked if existing (using the unique field in the column) and updated accordingly, new lines are added and the existing lines not matching any line of the file should be removed.

Some error treatment for:
- lines with empty values on the unique column field
- check if the user would like to keep or remove non-matching old lines

**Comment by nmadruga** [comment]
The list of issues to improve Lookup tables includes:

Issue 1: https://github.com/openmsupply/conforma-server/issues/816
Issue 2: https://github.com/openmsupply/conforma-web-app/issues/1048
Issue 3: **current**

**Comment by nmadruga** [comment]
> We should be able to select which is the unique column to use - which couldn't be edit

What should happen when we would like to update the unique field? Maybe when editing you are allowed to - and it should check if not editing to an already existing code

**Comment by CarlosNZ** [comment]
> What should happen when we would like to update the unique field? Maybe when editing you are allowed to - and it should check if not editing to an already existing code

If you change the unique field, then it's a new record. Plain and simple.

The unique id *is* the record, essentially, if you change it, then you've effectively removed one record and added a different one.

**Comment by nmadruga** [comment]
> > What should happen when we would like to update the unique field? Maybe when editing you are allowed to - and it should check if not editing to an already existing code
> 
> If you change the unique field, then it's a new record. Plain and simple.
> 
> The unique id _is_ the record, essentially, if you change it, then you've effectively removed one record and added a different one.

Yes, I agree. In the case of re-importing. 

But my concern was - what you you need to **update** the existing field code. Should we allow this on the UI?

**Comment by CarlosNZ** [comment]
This is all done now
