### ISSUE TITLE
addition fallback returns "null" string in stead of null value

### ISSUE THREAD

**Issue by fergie-nz** [msupply-foundation/conforma-web-app#1521]
When an addition element contains no values, it will return a "null" string instead of a null value.

Currently you can define an explicit NULL value fallback as a workaround

**Comment by CarlosNZ** [comment]
> When an addition element contains no values, it will return a "null" string instead of a null value.

It'll only do this if you're trying to concatenate `null` with a string, e.g. `null + "value"` => `"nullvalue"`. This is expected, as that's exactly what javascript does if you add `null  + "value"`.

Do you have a specific example of an expression that doesn't return what you think it should? And if so, what does it return, and what do you think it should?

These all return what I would expect:

```js
{
  operator: "+",
  children: []
} // => [ ]

{
  operator: "+",
  children: [ null ]
} // => null

{
  operator: "+",
  children: [ null, "something else" ]
} // => "nullsomething else"
```

**Comment by CarlosNZ** [comment]
Don't think this is a problem, and will be replaced by improved evaluator soon anyway
