### ISSUE TITLE
"Always reviewable" not working properly

### ISSUE THREAD

**Issue by CarlosNZ** [msupply-foundation/conforma-web-app#1537]
This needs more investigation, not 100% clear that this is the problem, but it appears that questions that have been marked "Always reviewable" are not in fact reviewable if the applicant made no response.

**Comment by CarlosNZ** [comment]
Also, please double-check this behaviour as part of this issue: https://github.com/openmsupply/conforma-web-app/pull/1514/files/2f5df797cee618935c89bce1685645cf148d8537#r1247267859

**Comment by LaurenceHolding** [comment]
Testing notes: Always Reviewable

TBC

**Comment by LaurenceHolding** [comment]
**Testing notes: Optional (if no application response)** 

Questions with the following requirement:
![image](https://github.com/openmsupply/conforma-web-app/assets/126527491/1dc4d15a-b289-43b6-99f6-9adeb7399f6a)

Must be reviewed when the applicant has provided a response
![image](https://github.com/openmsupply/conforma-web-app/assets/126527491/ab810772-6e3d-4d46-a783-073839339b63)

Can be reviewed (but don't have to be) when the applicant has not provided a response.
![image](https://github.com/openmsupply/conforma-web-app/assets/126527491/0496081e-730f-4253-9de8-f5be3986ea82)

So this works as it should. A potential alternative but doesn't completely serve the same purpose.

**Comment by CarlosNZ** [comment]
> So this works as it should. A potential alternative but doesn't completely serve the same purpose.

I think the case I noticed where it wasn't working correctly is when "Is Reviewable" is set to "Always reviewable", and then the applicant doesn't enter a response. The reviewer should still be able to review the element, but I don't think this was working reliably.

**Comment by LaurenceHolding** [comment]
> > So this works as it should. A potential alternative but doesn't completely serve the same purpose.
> 
> I think the case I noticed where it wasn't working correctly is when "Is Reviewable" is set to "Always reviewable", and then the applicant doesn't enter a response. The reviewer should still be able to review the element, but I don't think this was working reliably.

Sorry, I was testing them both as a comparison but ended up doing it backwards. So I found the same issue you've raised where if the question is set as always reviewable, it can't actually be reviewed if the applicant doesn't submit anything. The optional review method kind of works, as it allows the reviewer to review even if nothing is submitted, but ideally the always reviewable option would **require** the reviewer to review regardless.

**Comment by CarlosNZ** [comment]
> but ideally the always reviewable option would **require** the reviewer to review regardless.

Right, yes. That's the one. Thanks for confirming the problem -- I'll look at it at some point. (I don't think there's any actual use cases that are currently affected by this, are there?)

**Comment by jagoje** [comment]
Moving this to TBD column. Should be added to development backlog for future discussion.

**Comment by CarlosNZ** [comment]
This should be fixed now -- on Demo4 and Demo5.
