### ISSUE TITLE
Document Modal viewer

### ISSUE THREAD

**Issue by CarlosNZ** [msupply-foundation/conforma-web-app#1549]
- Probably needs to be a configurable option and not the default
- Is there a way to not download the package when this module is not in use?

### Implementation

Will probably either:
- use this package: https://github.com/mikecousins/react-pdf-js
- display in an iframe

Either way, it'll render in a modal overlay (Semantic UI)

### Issues:

- [x] #1559
- [x] #1560 
- [x] #1561

**Comment by jagoje** [comment]
**Initial Requirements**

As provided by PSM:

- The modal box should be triggered by clicking a button
- The modal should be implemented only on the Internal user side
- The modal, should be present in all types of screen
- They also provided the following as an example of the functionality: https://drive.google.com/file/d/1L8M5xAsfyv0KkFdralSnZaTuY7yi2Xzh/view

**Comment by CarlosNZ** [comment]
> * The modal should be implemented only on the Internal user side

Why? The applicant should be able to look at their own document after uploading it, surely? (And it's a lot more work to make it only for internal, and not consistent with our normal approach)

> The modal, should be present in all types of screen

What does this mean, exactly? (And doesn't that contradict the previous one?)

**Comment by jagoje** [comment]
Hi Carl,

**Comment by CarlosNZ** [comment]
Done !🥳
