### ISSUE TITLE
Grant Permissions Template - Checkboxes not loading

### ISSUE THREAD

**Issue by jagoje** [msupply-foundation/conforma-web-app#1622]
Bug noted:

Live server:

![Image](https://github.com/msupply-foundation/conforma-web-app/assets/88009219/dd164c79-8e1b-4ed0-bbae-b11547e04191)

**Comment by CarlosNZ** [comment]
> @CarlosNZ - Can this please be moved to the templates repo? I do not have permission for that.

You can't actually transfer issues between public and private repos -- it's a dumb Github restriction. You'll have to just re-create it and close this one sorry.

**Comment by jagoje** [comment]
@CarlosNZ  - Happy for you to close once the template is updated on sirema live server

**Comment by CarlosNZ** [comment]
Okay, this is fixed in latest build and on both servers now.
