### ISSUE TITLE
Setting to specify that a particular review stage/level can only be assigned to a single person

### ISSUE THREAD

**Issue by CarlosNZ** [msupply-foundation/conforma-web-app#1628]
I.e. Apply all sections or none.

This is already how it works for higher levels, so just need to replicate what the UI does. 

Will need to add a new field to `template_stage_review_level` table too. 

And add a control to the Template builder.

Estimated DEV time: ~ 1 day

**Comment by jagoje** [comment]
@CarlosNZ - This one will need to go ahead and put under the UAT Angola job code.

Thanks.

**Comment by CarlosNZ** [comment]
Have made progress with this. Test version on 50008 now. 

See new control to restrict levels:
![Screenshot 2024-04-19 at 10 23 26 AM](https://github.com/msupply-foundation/conforma-web-app/assets/5456533/d927131d-9b6a-4d9d-842c-2cf1d9fc7cc1)
