### ISSUE TITLE
Front-end improvements to application list

### ISSUE THREAD

**Issue by CarlosNZ** [msupply-foundation/conforma-web-app#1635]
The bulk of the improvement will be done in the database (as per https://github.com/msupply-foundation/conforma-server/issues/1103), but there are a few things we can do in front-end to help:

- make sure all queries get cancelled if user changes UI away from needing it
- debounce filter changes
- make sure the list query only fires *once* when table loads/re-renders
- cache the Reviewer, Assigner and Applicant lists in the filters, as these don't change often (and these queries also compete with the main list query)
  - if we cache the full list, then when the user types in the filter input to narrow the list, we should just filter locally rather than making new queries
- the Dashboard filter counts should speed up considerably as a result of [database improvements](https://github.com/msupply-foundation/conforma-server/issues/1103), but there's still a lot of them happening simultaneously, so maybe there's some efficiency improvement we can make here?
- SummaryView elements are still re-running all the dynamic parameter evaluations for every question on each render. This is unnecessary as we already have the "evaluatedParameters" field on the response (the values at the time the applicant submitted) to avoid incorrect "live" evaluations. (We do have an exception, for "showLiveParameters" when explicitly stated, but we can work around this).

**Comment by andreievg** [comment]
A small thing i found, userId in useApplicationList was not set at the start, and was causing two queries to back end.

Also there seems to be double the amount of queries to back end for dashboard filters (not sure why).

**Comment by CarlosNZ** [comment]
Done
