### ISSUE TITLE
Bug with navigating to summary page

### ISSUE THREAD

**Issue by andreievg** [msupply-foundation/conforma-web-app#566]
Try to go to http://localhost:3000/application/101/summary

i am getting constant redirects (could be a data issue ?)

**Comment by nmadruga** [comment]
Yes, it's a problem with this application - created before anything else was in place, so it's missing many data

**Comment by nmadruga** [comment]
Maybe this issue could be only to remove it from the db

**Comment by CarlosNZ** [comment]
Don't think a problem any more
